name: dio_log_plus
description: A plug-in that captures requests and views them within the application, providing functions such as request replication and JSON expansion
version: 4.0.0
homepage: https://github.com/jawa0919/dio_log_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ">=5.0.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
